<img src="/images/logo.png" alt="Vira Logo" class="image-align" height="160" style='<?= $params['lang'] == 'en' ? 'margin-bottom: 20px;' : '' ?>'/>
<display-header style='line-height: 40px'>
    <brand style='font-variant: small-caps;'><?= get_trans('company_name') ?></brand><br />
    <small style='margin-bottom:-100px;font-family: "Dancing Script"'>
        <?= get_trans('company_slogans') ?>
    </small>
</display-header>
<div style='padding:30px 0 20px 0; font-family: "Crimson Text"!important'>
	<div class='container' style='padding: 0; font-size: 30px; font-weight: 500'>
		<?= get_trans('company_about') ?>:
	</div>
	<div class='container' style='padding: 20px 3%; text-align: center; font-size: 22px; text-align: justify;'>
		<?= get_trans('aboutus_text') ?>
	</div>
</div>
