</div>
<!--/CONTAINER-->
<!--JS-->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
<script src="/js/jquery.plugin.min.js" type="text/javascript"></script>
<script src="/js/jquery.countdown.min.js" type="text/javascript"></script>
<script src="/js/jquery.countdown-<?= $params['lang'] ?>.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#defaultCountdown').countdown({until: new Date(<?= "${target_launch_date[0]}, ${target_launch_date[1]}, ${target_launch_date[2]}" ?>)});
    });
</script>
</body>
</html>